language: python

python:
  - "3.5"
  - "3.6"      # current detault Python on Travis CI
  - "3.7"

os:
  - linux
  - windows
  - osx

install:
  - pip install -r requirements.txt

script:
  - pytest -s -v --pyargs triplinker
